import puppeteer from 'puppeteer'
import { formatCurrency, formatAmount } from './currency-utils'

export interface FinancialReportData {
  title: string
  generatedAt: string
  generatedBy: string
  summary: {
    totalPayments: number
    totalAmount: number
    outstandingAmount: number
    paymentMethods: Record<string, number>
  }
  payments: Array<{
    id: string
    studentName: string
    feeName: string
    amount: number
    paymentDate: string
    paymentMethod: string
    receiptNumber: string
    status: string
  }>
  feeStructures: Array<{
    id: string
    name: string
    level: string
    amount: number
    dueDate: string
    status: string
  }>
  studentFeeAssignments: Array<{
    id: string
    studentName: string
    feeStructureName: string
    totalAmount: number
    amountPaid: number
    balance: number
    status: string
    dueDate: string
  }>
}

export interface PDFOptions {
  format?: 'A4' | 'Letter'
  margin?: {
    top: string
    right: string
    bottom: string
    left: string
  }
  header?: {
    title: string
    subtitle?: string
    logo?: string
  }
  footer?: {
    text: string
    pageNumbers?: boolean
  }
}

export class PDFGenerator {
  private browser: any | null = null

  async initialize() {
    if (!this.browser) {
      try {
        // Use different launch options for different environments
        const launchOptions: any = {
          headless: 'new',
          args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--disable-gpu'
          ]
        }

        // Add executable path for production environments
        if (process.env.NODE_ENV === 'production') {
          launchOptions.executablePath = process.env.PUPPETEER_EXECUTABLE_PATH || undefined
        }

        this.browser = await puppeteer.launch(launchOptions)
        console.log('Puppeteer browser initialized successfully')
      } catch (error) {
        console.error('Failed to initialize Puppeteer browser:', error)
        throw new Error(`Browser initialization failed: ${error instanceof Error ? error.message : 'Unknown error'}`)
      }
    }
  }

  async close() {
    if (this.browser) {
      try {
        await this.browser.close()
        this.browser = null
        console.log('Puppeteer browser closed successfully')
      } catch (error) {
        console.error('Error closing browser:', error)
      }
    }
  }

  private generateHTML(data: FinancialReportData, options: PDFOptions = {}): string {
    const {
      format = 'A4',
      margin = { top: '20mm', right: '20mm', bottom: '20mm', left: '20mm' },
      header = { title: 'Financial Report' },
      footer = { text: 'Generated by School Management System', pageNumbers: true }
    } = options

    const totalAmount = formatCurrency(data.summary.totalAmount)
    const outstandingAmount = formatCurrency(data.summary.outstandingAmount)

    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <title>${data.title}</title>
          <style>
            @page {
              size: ${format};
              margin: ${margin.top} ${margin.right} ${margin.bottom} ${margin.left};
            }
            
            body {
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
              line-height: 1.6;
              color: #333;
              margin: 0;
              padding: 0;
            }
            
            .header {
              text-align: center;
              border-bottom: 2px solid #2563eb;
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            
            .header h1 {
              color: #2563eb;
              margin: 0;
              font-size: 24px;
              font-weight: bold;
            }
            
            .header .subtitle {
              color: #6b7280;
              margin: 5px 0 0 0;
              font-size: 14px;
            }
            
            .summary-section {
              background: #f8fafc;
              border: 1px solid #e2e8f0;
              border-radius: 8px;
              padding: 20px;
              margin-bottom: 30px;
            }
            
            .summary-grid {
              display: grid;
              grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
              gap: 20px;
              margin-bottom: 20px;
            }
            
            .summary-item {
              text-align: center;
              padding: 15px;
              background: white;
              border-radius: 6px;
              border: 1px solid #e2e8f0;
            }
            
            .summary-item h3 {
              margin: 0 0 10px 0;
              color: #374151;
              font-size: 14px;
              font-weight: 600;
            }
            
            .summary-item .value {
              font-size: 24px;
              font-weight: bold;
              color: #2563eb;
            }
            
            .summary-item .amount {
              font-size: 20px;
              font-weight: bold;
              color: #059669;
            }
            
            .summary-item .outstanding {
              color: #dc2626;
            }
            
            .section {
              margin-bottom: 30px;
            }
            
            .section h2 {
              color: #1f2937;
              border-bottom: 1px solid #d1d5db;
              padding-bottom: 10px;
              margin-bottom: 20px;
              font-size: 18px;
            }
            
            table {
              width: 100%;
              border-collapse: collapse;
              margin-bottom: 20px;
              font-size: 12px;
            }
            
            th {
              background: #f3f4f6;
              border: 1px solid #d1d5db;
              padding: 12px 8px;
              text-align: left;
              font-weight: 600;
              color: #374151;
            }
            
            td {
              border: 1px solid #d1d5db;
              padding: 10px 8px;
              vertical-align: top;
            }
            
            tr:nth-child(even) {
              background: #f9fafb;
            }
            
            .status-badge {
              padding: 4px 8px;
              border-radius: 4px;
              font-size: 11px;
              font-weight: 500;
              text-transform: uppercase;
            }
            
            .status-completed { background: #dcfce7; color: #166534; }
            .status-paid { background: #dcfce7; color: #166534; }
            .status-partial { background: #fef3c7; color: #92400e; }
            .status-pending { background: #dbeafe; color: #1e40af; }
            .status-overdue { background: #fee2e2; color: #991b1b; }
            
            .footer {
              position: fixed;
              bottom: 0;
              left: 0;
              right: 0;
              text-align: center;
              padding: 10px;
              border-top: 1px solid #e5e7eb;
              background: white;
              font-size: 11px;
              color: #6b7280;
            }
            
            .page-break {
              page-break-before: always;
            }
            
            .payment-methods {
              display: grid;
              grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
              gap: 10px;
              margin-top: 15px;
            }
            
            .payment-method {
              background: white;
              padding: 10px;
              border-radius: 4px;
              border: 1px solid #e2e8f0;
              text-align: center;
            }
            
            .payment-method .method {
              font-weight: 600;
              color: #374151;
              margin-bottom: 5px;
            }
            
            .payment-method .amount {
              color: #059669;
              font-weight: 500;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${header.title}</h1>
            <div class="subtitle">${data.title}</div>
            <div class="subtitle">Generated on ${new Date(data.generatedAt).toLocaleDateString()} at ${new Date(data.generatedAt).toLocaleTimeString()}</div>
            <div class="subtitle">Generated by: ${data.generatedBy}</div>
          </div>
          
          <div class="summary-section">
            <h2>Financial Summary</h2>
            <div class="summary-grid">
              <div class="summary-item">
                <h3>Total Payments</h3>
                <div class="value">${data.summary.totalPayments}</div>
              </div>
              <div class="summary-item">
                <h3>Total Amount Collected</h3>
                <div class="amount">${totalAmount}</div>
              </div>
              <div class="summary-item">
                <h3>Outstanding Amount</h3>
                <div class="amount outstanding">${outstandingAmount}</div>
              </div>
            </div>
            
            <div class="payment-methods">
              <h3>Payments by Method</h3>
              ${Object.entries(data.summary.paymentMethods).map(([method, amount]) => `
                <div class="payment-method">
                  <div class="method">${method.replace('_', ' ').toUpperCase()}</div>
                  <div class="amount">${formatCurrency(amount)}</div>
                </div>
              `).join('')}
            </div>
          </div>
          
          ${data.payments.length > 0 ? `
            <div class="section">
              <h2>Payment Records (${data.payments.length})</h2>
              <table>
                <thead>
                  <tr>
                    <th>Receipt #</th>
                    <th>Student</th>
                    <th>Fee</th>
                    <th>Amount</th>
                    <th>Date</th>
                    <th>Method</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  ${data.payments.map(payment => `
                    <tr>
                      <td>${payment.receiptNumber}</td>
                      <td>${payment.studentName}</td>
                      <td>${payment.feeName}</td>
                      <td>${formatCurrency(payment.amount)}</td>
                      <td>${new Date(payment.paymentDate).toLocaleDateString()}</td>
                      <td>${payment.paymentMethod.replace('_', ' ').toUpperCase()}</td>
                      <td><span class="status-badge status-${payment.status}">${payment.status}</span></td>
                    </tr>
                  `).join('')}
                </tbody>
              </table>
            </div>
          ` : ''}
          
          ${data.feeStructures.length > 0 ? `
            <div class="section page-break">
              <h2>Fee Structures (${data.feeStructures.length})</h2>
              <table>
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Level</th>
                    <th>Amount</th>
                    <th>Due Date</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  ${data.feeStructures.map(fee => `
                    <tr>
                      <td>${fee.name}</td>
                      <td>${fee.level}</td>
                      <td>${formatCurrency(fee.amount)}</td>
                      <td>${new Date(fee.dueDate).toLocaleDateString()}</td>
                      <td><span class="status-badge status-${fee.status}">${fee.status}</span></td>
                    </tr>
                  `).join('')}
                </tbody>
              </table>
            </div>
          ` : ''}
          
          ${data.studentFeeAssignments.length > 0 ? `
            <div class="section page-break">
              <h2>Student Fee Assignments (${data.studentFeeAssignments.length})</h2>
              <table>
                <thead>
                  <tr>
                    <th>Student</th>
                    <th>Fee Structure</th>
                    <th>Total Amount</th>
                    <th>Amount Paid</th>
                    <th>Balance</th>
                    <th>Due Date</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  ${data.studentFeeAssignments.map(assignment => `
                    <tr>
                      <td>${assignment.studentName}</td>
                      <td>${assignment.feeStructureName}</td>
                      <td>${formatCurrency(assignment.totalAmount)}</td>
                      <td>${formatCurrency(assignment.amountPaid)}</td>
                      <td>${formatCurrency(assignment.balance)}</td>
                      <td>${new Date(assignment.dueDate).toLocaleDateString()}</td>
                      <td><span class="status-badge status-${assignment.status}">${assignment.status}</span></td>
                    </tr>
                  `).join('')}
                </tbody>
              </table>
            </div>
          ` : ''}
          
          <div class="footer">
            ${footer.text} | Page <span class="pageNumber"></span>
          </div>
        </body>
      </html>
    `
  }

  async generateFinancialReport(data: FinancialReportData, options: PDFOptions = {}): Promise<Buffer> {
    try {
      await this.initialize()
      
      if (!this.browser) {
        throw new Error('Failed to initialize browser')
      }

      const page = await this.browser.newPage()
      
      try {
        const html = this.generateHTML(data, options)
        await page.setContent(html, { waitUntil: 'networkidle0' })
        
        const pdf = await page.pdf({
          format: options.format || 'A4',
          printBackground: true,
          margin: options.margin || {
            top: '20mm',
            right: '20mm',
            bottom: '20mm',
            left: '20mm'
          }
        })
        
        return pdf
      } finally {
        await page.close()
      }
    } catch (error) {
      console.error('Error generating PDF:', error)
      throw new Error(`PDF generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`)
    }
  }

  async generatePaymentReport(payments: any[], options: PDFOptions = {}): Promise<Buffer> {
    const data: FinancialReportData = {
      title: 'Payment Report',
      generatedAt: new Date().toISOString(),
      generatedBy: 'System',
      summary: {
        totalPayments: payments.length,
        totalAmount: payments.reduce((sum, p) => sum + p.amountPaid, 0),
        outstandingAmount: 0,
        paymentMethods: payments.reduce((acc, p) => {
          acc[p.paymentMethod] = (acc[p.paymentMethod] || 0) + p.amountPaid
          return acc
        }, {} as Record<string, number>)
      },
      payments: payments.map(p => ({
        id: p.id,
        studentName: p.studentName,
        feeName: p.feeName,
        amount: p.amountPaid,
        paymentDate: p.paymentDate,
        paymentMethod: p.paymentMethod,
        receiptNumber: p.receiptNumber,
        status: p.status
      })),
      feeStructures: [],
      studentFeeAssignments: []
    }

    return this.generateFinancialReport(data, {
      header: { title: 'Payment Report' },
      ...options
    })
  }

  async generateFeeStructureReport(feeStructures: any[], options: PDFOptions = {}): Promise<Buffer> {
    const data: FinancialReportData = {
      title: 'Fee Structure Report',
      generatedAt: new Date().toISOString(),
      generatedBy: 'System',
      summary: {
        totalPayments: 0,
        totalAmount: feeStructures.reduce((sum, f) => sum + f.amount, 0),
        outstandingAmount: 0,
        paymentMethods: {}
      },
      payments: [],
      feeStructures: feeStructures.map(f => ({
        id: f.id,
        name: f.name,
        level: f.level,
        amount: f.amount,
        dueDate: f.dueDate,
        status: f.isActive ? 'active' : 'inactive'
      })),
      studentFeeAssignments: []
    }

    return this.generateFinancialReport(data, {
      header: { title: 'Fee Structure Report' },
      ...options
    })
  }

  async generateOutstandingFeesReport(assignments: any[], options: PDFOptions = {}): Promise<Buffer> {
    const outstandingAssignments = assignments.filter(a => a.balance > 0)
    
    const data: FinancialReportData = {
      title: 'Outstanding Fees Report',
      generatedAt: new Date().toISOString(),
      generatedBy: 'System',
      summary: {
        totalPayments: 0,
        totalAmount: outstandingAssignments.reduce((sum, a) => sum + a.totalAmount, 0),
        outstandingAmount: outstandingAssignments.reduce((sum, a) => sum + a.balance, 0),
        paymentMethods: {}
      },
      payments: [],
      feeStructures: [],
      studentFeeAssignments: outstandingAssignments.map(a => ({
        id: a.id,
        studentName: a.studentName,
        feeStructureName: a.feeStructureName,
        totalAmount: a.totalAmount,
        amountPaid: a.amountPaid,
        balance: a.balance,
        dueDate: a.dueDate,
        status: a.status
      }))
    }

    return this.generateFinancialReport(data, {
      header: { title: 'Outstanding Fees Report' },
      ...options
    })
  }
}

// Export a singleton instance
export const pdfGenerator = new PDFGenerator()
