-- Insert sample students for testing payment functionality
-- This script creates students with proper UUIDs that can be referenced in payments

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Insert sample students with proper UUIDs
INSERT INTO students (
    id,
    student_id,
    first_name,
    last_name,
    middle_name,
    email,
    phone,
    date_of_birth,
    gender,
    place_of_birth,
    nationality,
    religion,
    address,
    city,
    region,
    postal_code,
    subsystem,
    branch,
    class,
    previous_school,
    previous_class,
    is_new_student,
    total_fees,
    paid_fees,
    fees_status,
    enrollment_status,
    academic_year,
    status,
    enrollment_date
) VALUES
(
    uuid_generate_v4(),
    'STD-2024-001',
    'Marie',
    'Ngozi',
    'Atanga',
    'marie.ngozi@example.com',
    '+237 6XX XXX XXX',
    '2006-03-15',
    'Female',
    'Douala',
    'Cameroonian',
    'Christian',
    '123 Main Street, Douala',
    'Douala',
    'Littoral',
    '237',
    'english',
    'grammar',
    'Form 5 Science',
    'St. Joseph College',
    'Form 4 Science',
    true,
    75000.00,
    0.00,
    'pending',
    'enrolled',
    '2024-2025',
    'active',
    '2024-09-01'
),
(
    uuid_generate_v4(),
    'STD-2024-002',
    'Paul',
    'Biya',
    'Fru',
    'paul.biya@example.com',
    '+237 6XX XXX XXX',
    '2005-07-22',
    'Male',
    'Yaounde',
    'Cameroonian',
    'Christian',
    '456 Central Avenue, Yaounde',
    'Yaounde',
    'Centre',
    '237',
    'english',
    'grammar',
    'Form 5 Science',
    'Government High School',
    'Form 4 Science',
    true,
    75000.00,
    0.00,
    'pending',
    'enrolled',
    '2024-2025',
    'active',
    '2024-09-01'
),
(
    uuid_generate_v4(),
    'STD-2024-003',
    'Aminata',
    'Sali',
    '',
    'aminata.sali@example.com',
    '+237 6XX XXX XXX',
    '2006-11-08',
    'Female',
    'Bamenda',
    'Cameroonian',
    'Muslim',
    '789 Hill Street, Bamenda',
    'Bamenda',
    'North West',
    '237',
    'english',
    'grammar',
    'Form 4 Arts',
    'Sacred Heart College',
    'Form 3 Arts',
    true,
    70000.00,
    0.00,
    'pending',
    'enrolled',
    '2024-2025',
    'active',
    '2024-09-01'
),
(
    uuid_generate_v4(),
    'STD-2024-004',
    'Jean',
    'Claude',
    'Mbarga',
    'jean.claude@example.com',
    '+237 6XX XXX XXX',
    '2005-12-03',
    'Male',
    'Buea',
    'Cameroonian',
    'Christian',
    '321 Mountain Road, Buea',
    'Buea',
    'South West',
    '237',
    'french',
    'grammar',
    'Terminale C',
    'Lycee Bilingue',
    'Premiere C',
    true,
    80000.00,
    0.00,
    'pending',
    'enrolled',
    '2024-2025',
    'active',
    '2024-09-01'
),
(
    uuid_generate_v4(),
    'STD-2024-005',
    'Fatima',
    'Hassan',
    'Omar',
    'fatima.hassan@example.com',
    '+237 6XX XXX XXX',
    '2006-05-18',
    'Female',
    'Maroua',
    'Cameroonian',
    'Muslim',
    '654 Desert Street, Maroua',
    'Maroua',
    'Far North',
    '237',
    'french',
    'grammar',
    'Terminale D',
    'College Moderne',
    'Premiere D',
    true,
    80000.00,
    0.00,
    'pending',
    'enrolled',
    '2024-2025',
    'active',
    '2024-09-01'
)
ON CONFLICT (student_id) DO NOTHING;

-- Verify the students were inserted
SELECT 
    id,
    student_id,
    first_name,
    last_name,
    class,
    subsystem,
    branch,
    fees_status
FROM students 
WHERE student_id LIKE 'STD-2024-%'
ORDER BY student_id;

-- Show the UUIDs for reference
SELECT 
    student_id,
    id as uuid_id,
    first_name,
    last_name
FROM students 
WHERE student_id LIKE 'STD-2024-%'
ORDER BY student_id;
